In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
lb = pd.read_csv('leads_basic_details.csv')
ld = pd.read_csv('leads_demo_watched_details.csv')
li = pd.read_csv('leads_interaction_details.csv')
lr = pd.read_csv('leads_reasons_for_no_interest.csv')
sm = pd.read_csv('sales_managers_assigned_leads_details.csv')

In [3]:
lb.head()

,lead_id,age,gender,current_city,current_education,parent_occupation,lead_gen_source
0,USR1001,16,FEMALE,Hyderabad,Intermediate,Private Employee,social_media
1,USR1002,20,MALE,Bengaluru,B.Tech,Business,user_referrals
2,USR1003,20,FEMALE,Visakhapatnam,B.Tech,Lawyer,user_referrals
3,USR1004,16,MALE,Mumbai,Intermediate,IT Employee,user_referrals
4,USR1005,16,MALE,Chennai,Intermediate,Government Employee,user_referrals

In [25]:
def unique_values(dataset):
    for i in dataset.columns:
        print(f'\nUnique: {i.upper()}')
        unik_values = dataset[i].unique()
        print(f'Total unique values: {len(unik_values)}')
        print(unik_values)

In [26]:
unique_values(lb)

Unique: LEAD_ID
Total unique values: 360
['USR1001' 'USR1002' 'USR1003' 'USR1004' 'USR1005' 'USR1006' 'USR1007'
 'USR1008' 'USR1009' 'USR1010' 'USR1011' 'USR1012' 'USR1013' 'USR1014'
 'USR1015' 'USR1016' 'USR1017' 'USR1018' 'USR1019' 'USR1020' 'USR1021'
 'USR1022' 'USR1023' 'USR1024' 'USR1025' 'USR1026' 'USR1027' 'USR1028'
 'USR1029' 'USR1030' 'USR1031' 'USR1032' 'USR1033' 'USR1034' 'USR1035'
 'USR1036' 'USR1037' 'USR1038' 'USR1039' 'USR1040' 'USR1041' 'USR1042'
 'USR1043' 'USR1044' 'USR1045' 'USR1046' 'USR1047' 'USR1048' 'USR1049'
 'USR1050' 'USR1051' 'USR1052' 'USR1053' 'USR1054' 'USR1055' 'USR1056'
 'USR1057' 'USR1058' 'USR1059' 'USR1060' 'USR1061' 'USR1062' 'USR1063'
 'USR1064' 'USR1065' 'USR1066' 'USR1067' 'USR1068' 'USR1069' 'USR1070'
 'USR1071' 'USR1072' 'USR1073' 'USR1074' 'USR1075' 'USR1076' 'USR1077'
 'USR1078' 'USR1079' 'USR1080' 'USR1081' 'USR1082' 'USR1083' 'USR1084'
 'USR1085' 'USR1086' 'USR1087' 'USR1088' 'USR1089' 'USR1090' 'USR1091'
 'USR1092' 'USR1093' 'USR1094' 'USR1095' 'USR1096' 'USR1097' 'USR1098'
 'USR1099' 'USR1100' 'USR1101' 'USR1102' 'USR1103' 'USR1104' 'USR1105'
 'USR1106' 'USR1107' 'USR1108' 'USR1109' 'USR1110' 'USR1111' 'USR1112'
 'USR1113' 'USR1114' 'USR1115' 'USR1116' 'USR1117' 'USR1118' 'USR1119'
 'USR1120' 'USR1121' 'USR1122' 'USR1123' 'USR1124' 'USR1125' 'USR1126'
 'USR1127' 'USR1128' 'USR1129' 'USR1130' 'USR1131' 'USR1132' 'USR1133'
 'USR1134' 'USR1135' 'USR1136' 'USR1137' 'USR1138' 'USR1139' 'USR1140'
 'USR1141' 'USR1142' 'USR1143' 'USR1144' 'USR1145' 'USR1146' 'USR1147'
 'USR1148' 'USR1149' 'USR1150' 'USR1151' 'USR1152' 'USR1153' 'USR1154'
 'USR1155' 'USR1156' 'USR1157' 'USR1158' 'USR1159' 'USR1160' 'USR1161'
 'USR1162' 'USR1163' 'USR1164' 'USR1165' 'USR1166' 'USR1167' 'USR1168'
 'USR1169' 'USR1170' 'USR1171' 'USR1172' 'USR1173' 'USR1174' 'USR1175'
 'USR1176' 'USR1177' 'USR1178' 'USR1179' 'USR1180' 'USR1181' 'USR1182'
 'USR1183' 'USR1184' 'USR1185' 'USR1186' 'USR1187' 'USR1188' 'USR1189'
 'USR1190' 'USR1191' 'USR1192' 'USR1193' 'USR1194' 'USR1195' 'USR1196'
 'USR1197' 'USR1198' 'USR1199' 'USR1200' 'USR1201' 'USR1202' 'USR1203'
 'USR1204' 'USR1205' 'USR1206' 'USR1207' 'USR1208' 'USR1209' 'USR1210'
 'USR1211' 'USR1212' 'USR1213' 'USR1214' 'USR1215' 'USR1216' 'USR1217'
 'USR1218' 'USR1219' 'USR1220' 'USR1221' 'USR1222' 'USR1223' 'USR1224'
 'USR1225' 'USR1226' 'USR1227' 'USR1228' 'USR1229' 'USR1230' 'USR1231'
 'USR1232' 'USR1233' 'USR1234' 'USR1235' 'USR1236' 'USR1237' 'USR1238'
 'USR1239' 'USR1240' 'USR1241' 'USR1242' 'USR1243' 'USR1244' 'USR1245'
 'USR1246' 'USR1247' 'USR1248' 'USR1249' 'USR1250' 'USR1251' 'USR1252'
 'USR1253' 'USR1254' 'USR1255' 'USR1256' 'USR1257' 'USR1258' 'USR1259'
 'USR1260' 'USR1261' 'USR1262' 'USR1263' 'USR1264' 'USR1265' 'USR1266'
 'USR1267' 'USR1268' 'USR1269' 'USR1270' 'USR1271' 'USR1272' 'USR1273'
 'USR1274' 'USR1275' 'USR1276' 'USR1277' 'USR1278' 'USR1279' 'USR1280'
 'USR1281' 'USR1282' 'USR1283' 'USR1284' 'USR1285' 'USR1286' 'USR1287'
 'USR1288' 'USR1289' 'USR1290' 'USR1291' 'USR1292' 'USR1293' 'USR1294'
 'USR1295' 'USR1296' 'USR1297' 'USR1298' 'USR1299' 'USR1300' 'USR1301'
 'USR1302' 'USR1303' 'USR1304' 'USR1305' 'USR1306' 'USR1307' 'USR1308'
 'USR1309' 'USR1310' 'USR1311' 'USR1312' 'USR1313' 'USR1314' 'USR1315'
 'USR1316' 'USR1317' 'USR1318' 'USR1319' 'USR1320' 'USR1321' 'USR1322'
 'USR1323' 'USR1324' 'USR1325' 'USR1326' 'USR1327' 'USR1328' 'USR1329'
 'USR1330' 'USR1331' 'USR1332' 'USR1333' 'USR1334' 'USR1335' 'USR1336'
 'USR1337' 'USR1338' 'USR1339' 'USR1340' 'USR1341' 'USR1342' 'USR1343'
 'USR1344' 'USR1345' 'USR1346' 'USR1347' 'USR1348' 'USR1349' 'USR1350'
 'USR1351' 'USR1352' 'USR1353' 'USR1354' 'USR1355' 'USR1356' 'USR1357'
 'USR1358' 'USR1359' 'USR1360']

Unique: AGE
Total unique values: 9
[ 16  20  21  22  25  18  24 211 116]

Unique: GENDER
Total unique values: 2
['FEMALE' 'MALE']

Unique: CURRENT_CITY
Total unique values: 6
['Hyderabad' 'Bengaluru' 'Visakhapatnam' 'Mumbai' 'Chennai' 'Kochi']

Unique: CURRENT_EDUCATION
Total unique values: 6
['Intermediate' 'B.Tech' 'Degree' 'Looking for Job' '10th Completed'
 'Intermediate Completed']

Unique: PARENT_OCCUPATION
Total unique values: 7
['Private Employee' 'Business' 'Lawyer' 'IT Employee'
 'Government Employee' 'Doctor' 'Professor/Faculty']

Unique: LEAD_GEN_SOURCE
Total unique values: 5
['social_media' 'user_referrals' 'website' 'SEO' 'email_marketing']

In [14]:
ld.head()

   lead_id demo_watched_date language  watched_percentage
0  USR1002          1/4/2022   Telugu                  42
1  USR1003          1/7/2022   Telugu                  81
2  USR1004          1/2/2022   Telugu                  35
3  USR1005          1/3/2022    Hindi                  38
4  USR1006         1/12/2022    Hindi                  54

In [27]:
unique_values(ld)

Unique: LEAD_ID
Total unique values: 194
['USR1002' 'USR1003' 'USR1004' 'USR1005' 'USR1006' 'USR1007' 'USR1008'
 'USR1009' 'USR1010' 'USR1011' 'USR1012' 'USR1013' 'USR1014' 'USR1015'
 'USR1016' 'USR1017' 'USR1018' 'USR1019' 'USR1020' 'USR1021' 'USR1022'
 'USR1023' 'USR1024' 'USR1025' 'USR1026' 'USR1027' 'USR1028' 'USR1029'
 'USR1030' 'USR1031' 'USR1032' 'USR1033' 'USR1034' 'USR1035' 'USR1036'
 'USR1037' 'USR1038' 'USR1039' 'USR1040' 'USR1041' 'USR1042' 'USR1043'
 'USR1044' 'USR1045' 'USR1046' 'USR1047' 'USR1050' 'USR1051' 'USR1052'
 'USR1053' 'USR1055' 'USR1057' 'USR1058' 'USR1062' 'USR1063' 'USR1065'
 'USR1067' 'USR1070' 'USR1071' 'USR1072' 'USR1073' 'USR1075' 'USR1077'
 'USR1078' 'USR1082' 'USR1083' 'USR1087' 'USR1090' 'USR1091' 'USR1092'
 'USR1093' 'USR1095' 'USR1097' 'USR1098' 'USR1102' 'USR1103' 'USR1105'
 'USR1107' 'USR1110' 'USR1111' 'USR1112' 'USR1113' 'USR1115' 'USR1117'
 'USR1118' 'USR1122' 'USR1123' 'USR1127' 'USR1130' 'USR1131' 'USR1132'
 'USR1133' 'USR1135' 'USR1137' 'USR1138' 'USR1142' 'USR1143' 'USR1145'
 'USR1147' 'USR1150' 'USR1151' 'USR1152' 'USR1153' 'USR1155' 'USR1157'
 'USR1158' 'USR1162' 'USR1163' 'USR1167' 'USR1170' 'USR1171' 'USR1172'
 'USR1173' 'USR1175' 'USR1177' 'USR1178' 'USR1182' 'USR1183' 'USR1185'
 'USR1187' 'USR1190' 'USR1191' 'USR1192' 'USR1193' 'USR1195' 'USR1197'
 'USR1198' 'USR1202' 'USR1203' 'USR1207' 'USR1210' 'USR1211' 'USR1212'
 'USR1213' 'USR1215' 'USR1217' 'USR1218' 'USR1222' 'USR1223' 'USR1225'
 'USR1227' 'USR1230' 'USR1231' 'USR1232' 'USR1233' 'USR1235' 'USR1237'
 'USR1238' 'USR1242' 'USR1243' 'USR1247' 'USR1250' 'USR1251' 'USR1252'
 'USR1253' 'USR1255' 'USR1257' 'USR1258' 'USR1262' 'USR1263' 'USR1265'
 'USR1267' 'USR1270' 'USR1271' 'USR1272' 'USR1273' 'USR1275' 'USR1277'
 'USR1278' 'USR1282' 'USR1283' 'USR1287' 'USR1290' 'USR1291' 'USR1292'
 'USR1293' 'USR1295' 'USR1297' 'USR1298' 'USR1302' 'USR1303' 'USR1305'
 'USR1307' 'USR1310' 'USR1311' 'USR1312' 'USR1313' 'USR1314' 'USR1315'
 'USR1317' 'USR1318' 'USR1319' 'USR1343' 'USR1348']

Unique: DEMO_WATCHED_DATE
Total unique values: 32
['1/4/2022' '1/7/2022' '1/2/2022' '1/3/2022' '1/12/2022' '1/11/2022'
 '1/8/2022' '1/10/2022' '1/17/2022' '1/16/2022' '1/18/2022' '2/21/2022'
 '2/19/2022' '2/20/2022' '1/1/2022' '1/6/2022' '1/9/2022' '1/21/2022'
 '1/19/2022' '2/22/2022' '2/25/2022' '2/23/2022' '1/5/2022' '1/20/2022'
 '1/26/2022' '1/13/2022' '1/22/2022' '2/26/2022' '1/14/2022' '2/28/2022'
 '1/25/2022' '2/27/2022']

Unique: LANGUAGE
Total unique values: 3
['Telugu' 'Hindi' 'English']

Unique: WATCHED_PERCENTAGE
Total unique values: 86
[ 42  81  35  38  54  52  41  50  48  44  46  51  47  40  36 100   5  53
   8  10  11  14  17  20  23  55  73  26  29  32  56  59  62  60  65  70
  74  75  68  85  71  86  87  88  89   2  90  91  92  77  80  63  83  25
   3   4  30  45  64 510  37  66  67  49  57  69  61  95  15  12  13  72
  19 233  27  21  16  76  18  79  78  22  24  28  82  84]

In [15]:
li.head()

,jnr_sm_id,lead_id,lead_stage,call_done_date,call_status,call_reason
0,JNR1001MG,USR1001,lead,1/2/2022,successful,lead_introduction
1,JNR1001MG,USR1001,lead,1/2/2022,successful,demo_schedule
2,JNR1001MG,USR1002,lead,1/3/2022,successful,lead_introduction
3,JNR1001MG,USR1002,lead,1/4/2022,successful,demo_schedule
4,JNR1001MG,USR1002,awareness,1/5/2022,successful,post_demo_followup

In [28]:
unique_values(li)

Unique: JNR_SM_ID
Total unique values: 16
['JNR1001MG' 'JNR1002MG' 'JNR1003MG' 'JNR1004MG' 'JNR1005MG' 'JNR1006MG'
 'JNR1007MG' 'JNR1008MG' 'JNR1009MG' 'JNR1010MG' 'JNR1011MG' 'JNR1012MG'
 'JNR1013MG' 'JNR1014MG' 'JNR1015MG' 'JNR1016MG']

Unique: LEAD_ID
Total unique values: 358
['USR1001' 'USR1002' 'USR1003' 'USR1004' 'USR1005' 'USR1006' 'USR1007'
 'USR1008' 'USR1009' 'USR1010' 'USR1011' 'USR1012' 'USR1013' 'USR1014'
 'USR1015' 'USR1016' 'USR1017' 'USR1018' 'USR1019' 'USR1020' 'USR1021'
 'USR1022' 'USR1023' 'USR1024' 'USR1025' 'USR1026' 'USR1027' 'USR1028'
 'USR1029' 'USR1030' 'USR1031' 'USR1032' 'USR1033' 'USR1034' 'USR1035'
 'USR1036' 'USR1037' 'USR1038' 'USR1039' 'USR1040' 'USR1041' 'USR1042'
 'USR1043' 'USR1044' 'USR1045' 'USR1046' 'USR1047' 'USR1048' 'USR1049'
 'USR1050' 'USR1051' 'USR1052' 'USR1053' 'USR1054' 'USR1055' 'USR1056'
 'USR1057' 'USR1058' 'USR1059' 'USR1060' 'USR1061' 'USR1062' 'USR1063'
 'USR1064' 'USR1065' 'USR1066' 'USR1067' 'USR1068' 'USR1069' 'USR1070'
 'USR1071' 'USR1072' 'USR1073' 'USR1074' 'USR1075' 'USR1076' 'USR1077'
 'USR1078' 'USR1079' 'USR1080' 'USR1081' 'USR1082' 'USR1083' 'USR1084'
 'USR1085' 'USR1086' 'USR1087' 'USR1088' 'USR1089' 'USR1090' 'USR1091'
 'USR1092' 'USR1093' 'USR1094' 'USR1095' 'USR1096' 'USR1097' 'USR1098'
 'USR1099' 'USR1100' 'USR1101' 'USR1102' 'USR1103' 'USR1104' 'USR1105'
 'USR1106' 'USR1107' 'USR1108' 'USR1109' 'USR1110' 'USR1111' 'USR1112'
 'USR1113' 'USR1114' 'USR1115' 'USR1117' 'USR1118' 'USR1119' 'USR1120'
 'USR1121' 'USR1122' 'USR1123' 'USR1124' 'USR1125' 'USR1126' 'USR1127'
 'USR1128' 'USR1129' 'USR1130' 'USR1131' 'USR1132' 'USR1133' 'USR1134'
 'USR1135' 'USR1136' 'USR1137' 'USR1138' 'USR1139' 'USR1140' 'USR1141'
 'USR1142' 'USR1143' 'USR1144' 'USR1145' 'USR1146' 'USR1147' 'USR1148'
 'USR1149' 'USR1150' 'USR1151' 'USR1152' 'USR1153' 'USR1154' 'USR1155'
 'USR1156' 'USR1157' 'USR1158' 'USR1159' 'USR1160' 'USR1161' 'USR1162'
 'USR1163' 'USR1164' 'USR1165' 'USR1166' 'USR1167' 'USR1168' 'USR1169'
 'USR1170' 'USR1171' 'USR1172' 'USR1173' 'USR1174' 'USR1175' 'USR1176'
 'USR1177' 'USR1178' 'USR1179' 'USR1180' 'USR1181' 'USR1182' 'USR1183'
 'USR1184' 'USR1185' 'USR1186' 'USR1187' 'USR1188' 'USR1189' 'USR1190'
 'USR1191' 'USR1192' 'USR1193' 'USR1194' 'USR1195' 'USR1196' 'USR1197'
 'USR1198' 'USR1199' 'USR1200' 'USR1201' 'USR1202' 'USR1203' 'USR1204'
 'USR1205' 'USR1206' 'USR1207' 'USR1208' 'USR1209' 'USR1210' 'USR1211'
 'USR1212' 'USR1213' 'USR1214' 'USR1215' 'USR1216' 'USR1217' 'USR1218'
 'USR1219' 'USR1220' 'USR1221' 'USR1222' 'USR1223' 'USR1224' 'USR1225'
 'USR1226' 'USR1227' 'USR1228' 'USR1229' 'USR1230' 'USR1231' 'USR1232'
 'USR1233' 'USR1234' 'USR1235' 'USR1236' 'USR1237' 'USR1238' 'USR1239'
 'USR1240' 'USR1241' 'USR1242' 'USR1243' 'USR1244' 'USR1245' 'USR1246'
 'USR1247' 'USR1248' 'USR1249' 'USR1250' 'USR1251' 'USR1252' 'USR1253'
 'USR1254' 'USR1255' 'USR1256' 'USR1257' 'USR1258' 'USR1259' 'USR1260'
 'USR1261' 'USR1262' 'USR1263' 'USR1264' 'USR1265' 'USR1266' 'USR1267'
 'USR1268' 'USR1269' 'USR1270' 'USR1271' 'USR1272' 'USR1273' 'USR1274'
 'USR1275' 'USR1277' 'USR1278' 'USR1279' 'USR1280' 'USR1281' 'USR1282'
 'USR1283' 'USR1284' 'USR1285' 'USR1286' 'USR1287' 'USR1288' 'USR1289'
 'USR1290' 'USR1291' 'USR1292' 'USR1293' 'USR1294' 'USR1295' 'USR1296'
 'USR1297' 'USR1298' 'USR1299' 'USR1300' 'USR1301' 'USR1302' 'USR1303'
 'USR1304' 'USR1305' 'USR1306' 'USR1307' 'USR1308' 'USR1309' 'USR1310'
 'USR1311' 'USR1312' 'USR1313' 'USR1314' 'USR1315' 'USR1316' 'USR1317'
 'USR1318' 'USR1319' 'USR1320' 'USR1321' 'USR1322' 'USR1323' 'USR1324'
 'USR1325' 'USR1326' 'USR1327' 'USR1328' 'USR1329' 'USR1330' 'USR1331'
 'USR1332' 'USR1333' 'USR1334' 'USR1335' 'USR1336' 'USR1337' 'USR1338'
 'USR1339' 'USR1340' 'USR1341' 'USR1342' 'USR1343' 'USR1344' 'USR1345'
 'USR1346' 'USR1347' 'USR1348' 'USR1349' 'USR1350' 'USR1351' 'USR1352'
 'USR1353' 'USR1354' 'USR1355' 'USR1356' 'USR1357' 'USR1358' 'USR1359'
 'USR1360']

Unique: LEAD_STAGE
Total unique values: 4
['lead' 'awareness' 'consideration' 'conversion']

Unique: CALL_DONE_DATE
Total unique values: 40
['1/2/2022' '1/3/2022' '1/4/2022' '1/5/2022' '1/6/2022' '1/7/2022'
 '1/8/2022' '1/9/2022' '1/1/2022' '1/10/2022' '1/12/2022' '1/13/2022'
 '1/11/2022' '1/14/2022' '1/15/2022' '1/16/2022' '1/20/2022' '1/21/2022'
 '1/22/2022' '1/17/2022' '1/18/2022' '1/19/2022' '2/19/2022' '2/21/2022'
 '2/20/2022' '2/22/2022' '2/23/2022' '2/24/2022' '2/25/2022' '1/27/2022'
 '1/28/2022' '1/29/2022' '2/26/2022' '2/27/2022' '2/28/2022' '1/24/2022'
 '1/26/2022' '1/25/2022' '1/23/2022' '3/1/2022']

Unique: CALL_STATUS
Total unique values: 2
['successful' 'unsuccessful']

Unique: CALL_REASON
Total unique values: 8
['lead_introduction' 'demo_schedule' 'post_demo_followup'
 'followup_for_consideration' 'interested_for_conversion'
 'followup_for_conversion' 'successful_conversion' 'demo_not_attended']

In [16]:
lr.head()

,lead_id,reasons_for_not_interested_in_demo,reasons_for_not_interested_to_consider,reasons_for_not_interested_to_convert
0,USR1001,No time for student,NaN,NaN
1,USR1003,NaN,No time for student,NaN
2,USR1004,NaN,Wants offline classes,NaN
3,USR1005,NaN,Can't afford,NaN
4,USR1006,NaN,Student not interested in domain,NaN

In [29]:
unique_values(lr)

Unique: LEAD_ID
Total unique values: 294
['USR1001' 'USR1003' 'USR1004' 'USR1005' 'USR1006' 'USR1008' 'USR1009'
 'USR1010' 'USR1014' 'USR1015' 'USR1016' 'USR1018' 'USR1019' 'USR1020'
 'USR1021' 'USR1024' 'USR1026' 'USR1027' 'USR1028' 'USR1029' 'USR1030'
 'USR1034' 'USR1035' 'USR1036' 'USR1038' 'USR1039' 'USR1040' 'USR1041'
 'USR1043' 'USR1044' 'USR1045' 'USR1046' 'USR1048' 'USR1049' 'USR1050'
 'USR1054' 'USR1055' 'USR1056' 'USR1058' 'USR1059' 'USR1060' 'USR1061'
 'USR1064' 'USR1065' 'USR1066' 'USR1067' 'USR1068' 'USR1069' 'USR1070'
 'USR1071' 'USR1074' 'USR1075' 'USR1076' 'USR1077' 'USR1078' 'USR1079'
 'USR1080' 'USR1081' 'USR1082' 'USR1083' 'USR1084' 'USR1085' 'USR1086'
 'USR1087' 'USR1088' 'USR1089' 'USR1090' 'USR1091' 'USR1094' 'USR1095'
 'USR1096' 'USR1097' 'USR1098' 'USR1099' 'USR1100' 'USR1101' 'USR1104'
 'USR1105' 'USR1106' 'USR1107' 'USR1108' 'USR1109' 'USR1110' 'USR1111'
 'USR1114' 'USR1115' 'USR1117' 'USR1118' 'USR1119' 'USR1120' 'USR1121'
 'USR1122' 'USR1123' 'USR1124' 'USR1125' 'USR1126' 'USR1127' 'USR1128'
 'USR1129' 'USR1130' 'USR1131' 'USR1134' 'USR1135' 'USR1136' 'USR1137'
 'USR1138' 'USR1139' 'USR1140' 'USR1141' 'USR1144' 'USR1145' 'USR1146'
 'USR1147' 'USR1148' 'USR1149' 'USR1150' 'USR1151' 'USR1154' 'USR1155'
 'USR1156' 'USR1157' 'USR1158' 'USR1159' 'USR1160' 'USR1161' 'USR1162'
 'USR1163' 'USR1164' 'USR1165' 'USR1166' 'USR1167' 'USR1168' 'USR1169'
 'USR1170' 'USR1171' 'USR1174' 'USR1175' 'USR1176' 'USR1177' 'USR1178'
 'USR1179' 'USR1180' 'USR1181' 'USR1184' 'USR1185' 'USR1186' 'USR1187'
 'USR1188' 'USR1189' 'USR1190' 'USR1191' 'USR1194' 'USR1195' 'USR1196'
 'USR1197' 'USR1198' 'USR1199' 'USR1200' 'USR1201' 'USR1202' 'USR1203'
 'USR1204' 'USR1205' 'USR1206' 'USR1207' 'USR1208' 'USR1209' 'USR1210'
 'USR1211' 'USR1214' 'USR1215' 'USR1216' 'USR1217' 'USR1218' 'USR1219'
 'USR1220' 'USR1221' 'USR1224' 'USR1225' 'USR1226' 'USR1227' 'USR1228'
 'USR1229' 'USR1230' 'USR1231' 'USR1234' 'USR1235' 'USR1236' 'USR1237'
 'USR1238' 'USR1239' 'USR1240' 'USR1241' 'USR1242' 'USR1243' 'USR1244'
 'USR1245' 'USR1246' 'USR1247' 'USR1248' 'USR1249' 'USR1250' 'USR1251'
 'USR1254' 'USR1255' 'USR1256' 'USR1257' 'USR1258' 'USR1259' 'USR1260'
 'USR1261' 'USR1264' 'USR1265' 'USR1266' 'USR1267' 'USR1268' 'USR1269'
 'USR1270' 'USR1271' 'USR1274' 'USR1275' 'USR1277' 'USR1278' 'USR1279'
 'USR1280' 'USR1281' 'USR1282' 'USR1283' 'USR1284' 'USR1285' 'USR1286'
 'USR1287' 'USR1288' 'USR1289' 'USR1290' 'USR1291' 'USR1294' 'USR1295'
 'USR1296' 'USR1298' 'USR1299' 'USR1300' 'USR1301' 'USR1304' 'USR1305'
 'USR1306' 'USR1308' 'USR1309' 'USR1310' 'USR1315' 'USR1316' 'USR1318'
 'USR1319' 'USR1320' 'USR1321' 'USR1322' 'USR1323' 'USR1324' 'USR1325'
 'USR1326' 'USR1327' 'USR1328' 'USR1329' 'USR1330' 'USR1331' 'USR1332'
 'USR1333' 'USR1334' 'USR1335' 'USR1336' 'USR1337' 'USR1338' 'USR1339'
 'USR1340' 'USR1341' 'USR1342' 'USR1343' 'USR1344' 'USR1345' 'USR1346'
 'USR1347' 'USR1348' 'USR1349' 'USR1350' 'USR1351' 'USR1352' 'USR1353'
 'USR1354' 'USR1355' 'USR1356' 'USR1357' 'USR1358' 'USR1359' 'USR1360']

Unique: REASONS_FOR_NOT_INTERESTED_IN_DEMO
Total unique values: 7
['No time for student' nan 'Student not interested in domain'
 'Wants offline classes' "Can't afford" 'Cannot afford'
 'Will join in final year']

Unique: REASONS_FOR_NOT_INTERESTED_TO_CONSIDER
Total unique values: 6
[nan 'No time for student' 'Wants offline classes' "Can't afford"
 'Student not interested in domain' 'Will join in final year']

Unique: REASONS_FOR_NOT_INTERESTED_TO_CONVERT
Total unique values: 6
[nan "Can't afford" 'Will join in final year' 'No time for student'
 'Student not interested in domain' 'Wants offline classes']

In [17]:
sm.head()

  snr_sm_id  jnr_sm_id assigned_date  cycle  lead_id
0  SNR501MG  JNR1001MG      1/1/2022      1  USR1001
1  SNR501MG  JNR1001MG      1/1/2022      1  USR1002
2  SNR501MG  JNR1001MG      1/1/2022      1  USR1003
3  SNR501MG  JNR1001MG      1/1/2022      1  USR1004
4  SNR501MG  JNR1001MG      1/1/2022      1  USR1005

In [30]:
unique_values(sm)

Unique: SNR_SM_ID
Total unique values: 4
['SNR501MG' 'SNR502MG' 'SNR503MG' 'SNR504MG']

Unique: JNR_SM_ID
Total unique values: 16
['JNR1001MG' 'JNR1002MG' 'JNR1003MG' 'JNR1004MG' 'JNR1005MG' 'JNR1006MG'
 'JNR1007MG' 'JNR1008MG' 'JNR1009MG' 'JNR1010MG' 'JNR1011MG' 'JNR1012MG'
 'JNR1013MG' 'JNR1014MG' 'JNR1015MG' 'JNR1016MG']

Unique: ASSIGNED_DATE
Total unique values: 4
['1/1/2022' '1/8/2022' '1/15/2022' '2/19/2022']

Unique: CYCLE
Total unique values: 4
[1 2 3 4]

Unique: LEAD_ID
Total unique values: 360
['USR1001' 'USR1002' 'USR1003' 'USR1004' 'USR1005' 'USR1006' 'USR1007'
 'USR1008' 'USR1009' 'USR1010' 'USR1011' 'USR1012' 'USR1013' 'USR1014'
 'USR1015' 'USR1016' 'USR1017' 'USR1018' 'USR1019' 'USR1020' 'USR1021'
 'USR1022' 'USR1023' 'USR1024' 'USR1025' 'USR1026' 'USR1027' 'USR1028'
 'USR1029' 'USR1030' 'USR1031' 'USR1032' 'USR1033' 'USR1034' 'USR1035'
 'USR1036' 'USR1037' 'USR1038' 'USR1039' 'USR1040' 'USR1041' 'USR1042'
 'USR1043' 'USR1044' 'USR1045' 'USR1046' 'USR1047' 'USR1048' 'USR1049'
 'USR1050' 'USR1051' 'USR1052' 'USR1053' 'USR1054' 'USR1055' 'USR1056'
 'USR1057' 'USR1058' 'USR1059' 'USR1060' 'USR1061' 'USR1062' 'USR1063'
 'USR1064' 'USR1065' 'USR1066' 'USR1067' 'USR1068' 'USR1069' 'USR1070'
 'USR1071' 'USR1072' 'USR1073' 'USR1074' 'USR1075' 'USR1076' 'USR1077'
 'USR1078' 'USR1079' 'USR1080' 'USR1081' 'USR1082' 'USR1083' 'USR1084'
 'USR1085' 'USR1086' 'USR1087' 'USR1088' 'USR1089' 'USR1090' 'USR1091'
 'USR1092' 'USR1093' 'USR1094' 'USR1095' 'USR1096' 'USR1097' 'USR1098'
 'USR1099' 'USR1100' 'USR1101' 'USR1102' 'USR1103' 'USR1104' 'USR1105'
 'USR1106' 'USR1107' 'USR1108' 'USR1109' 'USR1110' 'USR1111' 'USR1112'
 'USR1113' 'USR1114' 'USR1115' 'USR1116' 'USR1117' 'USR1118' 'USR1119'
 'USR1120' 'USR1121' 'USR1122' 'USR1123' 'USR1124' 'USR1125' 'USR1126'
 'USR1127' 'USR1128' 'USR1129' 'USR1130' 'USR1131' 'USR1132' 'USR1133'
 'USR1134' 'USR1135' 'USR1136' 'USR1137' 'USR1138' 'USR1139' 'USR1140'
 'USR1141' 'USR1142' 'USR1143' 'USR1144' 'USR1145' 'USR1146' 'USR1147'
 'USR1148' 'USR1149' 'USR1150' 'USR1151' 'USR1152' 'USR1153' 'USR1154'
 'USR1155' 'USR1156' 'USR1157' 'USR1158' 'USR1159' 'USR1160' 'USR1161'
 'USR1162' 'USR1163' 'USR1164' 'USR1165' 'USR1166' 'USR1167' 'USR1168'
 'USR1169' 'USR1170' 'USR1171' 'USR1172' 'USR1173' 'USR1174' 'USR1175'
 'USR1176' 'USR1177' 'USR1178' 'USR1179' 'USR1180' 'USR1181' 'USR1182'
 'USR1183' 'USR1184' 'USR1185' 'USR1186' 'USR1187' 'USR1188' 'USR1189'
 'USR1190' 'USR1191' 'USR1192' 'USR1193' 'USR1194' 'USR1195' 'USR1196'
 'USR1197' 'USR1198' 'USR1199' 'USR1200' 'USR1201' 'USR1202' 'USR1203'
 'USR1204' 'USR1205' 'USR1206' 'USR1207' 'USR1208' 'USR1209' 'USR1210'
 'USR1211' 'USR1212' 'USR1213' 'USR1214' 'USR1215' 'USR1216' 'USR1217'
 'USR1218' 'USR1219' 'USR1220' 'USR1221' 'USR1222' 'USR1223' 'USR1224'
 'USR1225' 'USR1226' 'USR1227' 'USR1228' 'USR1229' 'USR1230' 'USR1231'
 'USR1232' 'USR1233' 'USR1234' 'USR1235' 'USR1236' 'USR1237' 'USR1238'
 'USR1239' 'USR1240' 'USR1241' 'USR1242' 'USR1243' 'USR1244' 'USR1245'
 'USR1246' 'USR1247' 'USR1248' 'USR1249' 'USR1250' 'USR1251' 'USR1252'
 'USR1253' 'USR1254' 'USR1255' 'USR1256' 'USR1257' 'USR1258' 'USR1259'
 'USR1260' 'USR1261' 'USR1262' 'USR1263' 'USR1264' 'USR1265' 'USR1266'
 'USR1267' 'USR1268' 'USR1269' 'USR1270' 'USR1271' 'USR1272' 'USR1273'
 'USR1274' 'USR1275' 'USR1276' 'USR1277' 'USR1278' 'USR1279' 'USR1280'
 'USR1281' 'USR1282' 'USR1283' 'USR1284' 'USR1285' 'USR1286' 'USR1287'
 'USR1288' 'USR1289' 'USR1290' 'USR1291' 'USR1292' 'USR1293' 'USR1294'
 'USR1295' 'USR1296' 'USR1297' 'USR1298' 'USR1299' 'USR1300' 'USR1301'
 'USR1302' 'USR1303' 'USR1304' 'USR1305' 'USR1306' 'USR1307' 'USR1308'
 'USR1309' 'USR1310' 'USR1311' 'USR1312' 'USR1313' 'USR1314' 'USR1315'
 'USR1316' 'USR1317' 'USR1318' 'USR1319' 'USR1320' 'USR1321' 'USR1322'
 'USR1323' 'USR1324' 'USR1325' 'USR1326' 'USR1327' 'USR1328' 'USR1329'
 'USR1330' 'USR1331' 'USR1332' 'USR1333' 'USR1334' 'USR1335' 'USR1336'
 'USR1337' 'USR1338' 'USR1339' 'USR1340' 'USR1341' 'USR1342' 'USR1343'
 'USR1344' 'USR1345' 'USR1346' 'USR1347' 'USR1348' 'USR1349' 'USR1350'
 'USR1351' 'USR1352' 'USR1353' 'USR1354' 'USR1355' 'USR1356' 'USR1357'
 'USR1358' 'USR1359' 'USR1360']